### ISSUE TITLE
getAllOutgoingPropagationConditions error on bus access

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#10]
In the following code snippet, the result for bus access is dependent on the method we connect the bus access. For example if I connect the buses like this:
connections
  bus access c1.ba1 -> c2.ba2;

then, the outgoing propagation from ba2 will not be retrieved even if the component has the error component propagations defined. The one from c1 will be retrieved.

However, the following model :
  bus access c1.ba1 <-> c2.ba2;
Will retrieve the list for both components.

I think the standard does not require to use a particular connection for bus access and the code would have the same behavior on both models.

for (OutgoingPropagationCondition opc : EMV2Util.getAllOutgoingPropagationConditions(aadlComponent.getComponentClassifier()))
{
handleOutgoingPropagationCondition (opc);
}

**Comment by reteprelief** [comment]
The standard states about access connections:
Data and bus access connections may be bidirectional or directional.
As convention I always declare bus connections bi-directional.
I am looking to clean up the access connection direction stuff for V3.
