### ISSUE TITLE
getAllErrorBehaviorTransitions inconsistent behavior

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#11]
The method getAllErrorBehaviorTransitions returns the transitions from both the component error behavior an the error behavior if the component has a component error behavior. If the component error behavior is not defined, it returns nothing.

The function shall at least returns the behavior of the error behavior if the component does not have a component error behavior.
So, to summarize, the function would returns the transitions from both the error behavior and the component error behavior.

**Comment by reteprelief** [comment]
works.
