### ISSUE TITLE
Type products in error paths not recognized as being in error propagation sets

### ISSUE THREAD

**Issue by brlarson** [osate/ErrorModelV2#110]
Related to #109 this also gets error messages:

abstract Two_Voter extends Voter
  features
    inputs : refined to in event data port port_type[2];
	properties
	  Replication::Correction => Omit;  --omit when error detected
	  Replication::n => 2;  --2x inputs
  annex EMV2
  {**
  	use types ErrorLibrary;
    error propagations
      inputs : in propagation 
        {ErrorLibrary::AsymmetricReplicatesError*ErrorLibrary::CommonErrors,
        	ErrorLibrary::SymmetricReplicatesError*ErrorLibrary::CommonErrors};
      result : out propagation 
        {ErrorLibrary::SymmetricReplicatesError*ErrorLibrary::CommonErrors,
        	ErrorLibrary::ItemOmission};
    flows
    --asymmetirc errors become item omission
      failsilent : error path inputs 
        {ErrorLibrary::AsymmetricReplicatesError*ErrorLibrary::CommonErrors}
        -> result {ErrorLibrary::ItemOmission}; 
    --symmetric errors pass through 
      pass : error path inputs {ErrorLibrary::SymmetricReplicatesError*ErrorLibrary::CommonErrors}
        -> result;  
    end propagations;
  **};
end Two_Voter;

ErrorLibrary::AsymmetricReplicatesError*ErrorLibrary::CommonErrors is explicitly included by in propagation.  This will be a problem because I'm trying to express any asymmetric error.  Thus ErrorLibrary::AsymmetricReplicatesError*ItemValueError wouldn't include ErrorLibrary::AsymmetricReplicatesError*OutOfRange.

**Comment by reteprelief** [comment]
Same as #109 
Fixed.
