### ISSUE TITLE
EMFTA export cannot use error super type

### ISSUE THREAD

**Issue by pbalsgaard** [osate/ErrorModelV2#124]
The EMFTA export cannot use an error type if it has been extended in a type hierarchy. Instead, it uses the last extension in listed in the hierarchy. This isn't how I expect it to behave, but I guess it could be intentional. For example, ErrorLibrary defines:
```
OutOfRange: type extends DetectableValueError;
BelowRange: type extends OutOfRange;
AboveRange: type extends OutOfRange;
```
If a model uses error propagations of `OutOfRange` type, when performing EMFTA export the errors will be treated as `AboveRange` type because it is the last extension of `OutOfRange`.

**Comment by pbalsgaard** [comment]
After spending more time with this, I think it's the expected behavior that when the supertype is used, all subtypes are substituted in. I expected the extensions to behave like system extensions in regular AADL.

**Comment by reteprelief** [comment]
You are correct in your observation.
