### ISSUE TITLE
use types not reused in component implementation

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#13]
If I defined a use types in the component type, this is not reused in the component implementation and I have to redefine it. The following model fails :
package testba

public

with ErrorLibrary;
with mylib;

system s
features 
   foo : out event port;
annex EMV2 {**
	use types ErrorLibrary;

	**};
end s;

system implementation s.i
annex EMV2 {**
	use behavior mylib::Simple;
		error propagations
		foo : out propagation {ItemComission};
	end propagations;
	**};
end s.i;

end testba;

and the following here parses without error:

package testba

public

with ErrorLibrary;
with mylib;

system s
features 
   foo : out event port;
annex EMV2 {**
	use types ErrorLibrary;
	error propagations
		foo : out propagation {ItemComission};
	end propagations;
	**};
end s;

system implementation s.i
annex EMV2 {**
	use behavior mylib::Simple;
	**};
end s.i;

end testba;

both should parse without error.

**Comment by reteprelief** [comment]
ItemComission  is misspelled. ItemCommission resolves correctly.
