### ISSUE TITLE
ErrorModelSerializer not working for unparsing error model subclause

### ISSUE THREAD

**Issue by rinsley** [osate/ErrorModelV2#136]
I am attempting to serialize a programmatically created AADL model with EMV2 annex statements. This worked with OSATE 2.2.1.

Now, it results in an error from the annex unparser stating that no context for the ErrorModelSubclause can be found.

I think this may be due to ErrorModelSerializer.xtend. This overrides the getContext() method from Serializer to provide a context for ErrorModelSubclauses. However, getContext() is deprecated in the latest version of XText and replaced by getIContext(), so the overriding of getContext() is no longer working and getIContext() is throwing an exception because no context can be found for ErrorModelSubclauses.

**Comment by sprocter** [comment]
Hi rinsley,

Can you post a [minimal working example](https://stackoverflow.com/help/mcve)? We've identified some possible solutions, but we're having trouble reproducing the error you have.

Thanks
-- Sam

**Comment by joeseibel** [comment]
Fixed by 61c1e565be4dcbb434d9f923d82afd3c99d0fc4d.

**Comment by rinsley** [comment]
Hi, sorry for the delayed response. That commit solved the problem, thanks!
