### ISSUE TITLE
The import org.osate.aadl2.errormodel.PropagationGraph cannot be resolved

### ISSUE THREAD

**Issue by brlarson** [osate/ErrorModelV2#147]
In org.osate.aadl2.errormodel.analysis.PropagateErrorSources, the import org.osate.aadl2.errormodel.PropagationGraph cannot be resolved.  
Contained classes PropagationGraph, PropagationPath, PropagationPathEnd, and util.Util are not found which leads to a cascade of errors.  Searching for "PropagationGraph" found no package of that name in the workspace.

The Git repo was pulled on Halloween, 2017.

Description	Resource	Path	Location	Type
The import org.osate.aadl2.errormodel.PropagationGraph cannot be resolved	PropagateErrorSources.java	/org.osate.aadl2.errormodel.analysis/src/org/osate/aadl2/errormodel/analysis	line 50	Java Problem

**Comment by lwrage** [comment]
There's a new project org.osate.aadl2.errormodel.propagationgraph. You need to import it from git.
There are also other new projects for the rewritten FTA.

**Comment by brlarson** [comment]
Thanks, got it.

On Nov 4, 2017, at 5:01 PM, Lutz Wrage <notifications@github.com<mailto:notifications@github.com>> wrote:


There's a new project org.osate.aadl2.errormodel.propagationgraph. You need to import it from git.
There are also other new projects for the rewritten FTA.
