### ISSUE TITLE
hasCompositeErrorBehavior return false is the component has an error composite without error component

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#25]
With the following model, the hasCompositeErrorBehavior returns false.

system implementation assembly.i
subcomponents
	s1_1 : system sender.i1;
	s1_2 : system sender.i1;
	s2_1 : system sender.i2;
	s2_2 : system sender.i2;
	s3_1 : system sender.i3;
	r1_1 : system receiver.i1;
	r1_2 : system receiver.i1;
	r2_1 : system receiver.i2;
	r2_2 : system receiver.i2;
connections
	c1 : port s1_1.valueout -> r1_1.valuein;
	c2 : port s1_2.valueout -> r1_1.valuein;
	c3 : port s3_1.valueout -> r2_1.valuein; 
annex EMV2 {**
	use types ErrorLibrary;
	use behavior ErrorModelLibrary::Simple;
	
	composite error behavior
	states
		[ r2_1.Failed ]-> Failed;
	end composite;
**};	
end assembly.i;

With the following model, it returns true. The difference is the definition of the component error behavior.

system implementation assembly.i
subcomponents
	s1_1 : system sender.i1;
	s1_2 : system sender.i1;
	s2_1 : system sender.i2;
	s2_2 : system sender.i2;
	s3_1 : system sender.i3;
	r1_1 : system receiver.i1;
	r1_2 : system receiver.i1;
	r2_1 : system receiver.i2;
	r2_2 : system receiver.i2;
connections
	c1 : port s1_1.valueout -> r1_1.valuein;
	c2 : port s1_2.valueout -> r1_1.valuein;
	c3 : port s3_1.valueout -> r2_1.valuein; 
annex EMV2 {**
	use types ErrorLibrary;
	use behavior ErrorModelLibrary::Simple;
	
	component error behavior
	end component;
	
	composite error behavior
	states
		[ r2_1.Failed ]-> Failed;
	end composite;
**};	
end assembly.i;

**Comment by reteprelief** [comment]
works ok now on examples.
