### ISSUE TITLE
get EMV properties on component classifier and implementation

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#31]
When trying to retrieve the property values on component classifier or implementation, there are some issues if both classifier and implementation have error model sublauses. 

To reproduce the bug, use the following model https://github.com/osate/examples/blob/master/error-model/FHA/fha-states.aadl and try to generate the FHA for main.i and main.i2. It will not work for the second system even if the information are the same. If we remove the error subclause from subsys2, it finally work.

**Comment by reteprelief** [comment]
fixed.
