### ISSUE TITLE
AnalysisModel fails to get all incoming/outgoing error propagations path

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#45]
When using the AnalysisModel class, it turns out that it does not record any error-model error path. When using the CMA action (Analyses->Fault->Common Mode Analysis), the Analysis Model does not contain anything.

A test model can be found on https://github.com/osate/examples/tree/master/core-examples/emv2-cca-cma

When the error path are retrieved is in https://github.com/osate/ErrorModelV2/blob/develop/org.osate.aadl2.errormodel.analysis/src/org/osate/aadl2/errormodel/analysis/cma/CMAUtils.java see the method getAllErrorSources. For each incoming error propagations, we try to find the related error path. But no error path are recorded when creating the AnalysisModel object. I tried to print the error path but it does not work. See https://github.com/osate/ErrorModelV2/blob/develop/org.osate.aadl2.errormodel.analysis/src/org/osate/aadl2/errormodel/analysis/actions/CMAAction.java line 85 for debug information.

**Comment by reteprelief** [comment]
AnalysisModel has been reworked as PropagationGraph and addresses the problem.
