### ISSUE TITLE
Error behavior branch transitions don't check probabilities when using named constants

### ISSUE THREAD

**Issue by sprocter** [osate/ErrorModelV2#46]
Probabilities assigned to transition branches in error behavior blocks should add up to 1.0. This is enforced by OSATE2 if you use literal values, but it is not enforced if you use constant identifiers.  A minimal working example can be found at https://gist.github.com/sprocter/d46c4a317e9791f31317.

**Comment by reteprelief** [comment]
Works now (Dec 2017)
