### ISSUE TITLE
Error when getting the Error Path using AnalysisModel class

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#56]
When trying to get the error path using the AnalysisModel class, only part of the path is retrieved. Considering the model on https://github.com/osate/examples/blob/master/error-model/Basic/basicflows.aadl

When getting the ErrorPath error from the sender component, it returns a path between the middle and receiver component. Using the getAllRerversePropagationPaths with the receiver component instance should return an error path where the source is the sender component.

**Comment by reteprelief** [comment]
We switched to PropagationGraph to replace AnalysisModel
