### ISSUE TITLE
Fix outline view by providing names

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#59]
The outline view for the EMV2 is full of unnamed elements (see below). One thing would be to support names within this view (or at least that they are showing, such as a condition, a propagation, etc.).

![unamed-emv2](https://cloud.githubusercontent.com/assets/993972/3736402/6ec065b4-172d-11e4-966a-e4dc2561d5d8.png)

**Comment by reteprelief** [comment]
fixed.
