### ISSUE TITLE
Properties not applied to error source

### ISSUE THREAD

**Issue by brlarson** [osate/ErrorModelV2#68]
I get these error reports:
Property EMV2::Hazards does not apply to inf	Devices.aadl	/isolette-ksu/aadl/packages	line: 19 /isolette-ksu/aadl/packages/Devices.aadl	Xtext Check (fast)
Property EMV2::Likelihood does not apply to inf	Devices.aadl	/isolette-ksu/aadl/packages	line: 28 /isolette-ksu/aadl/packages/Devices.aadl	Xtext Check (fast)
Property EMV2::Severity does not apply to inf	Devices.aadl	/isolette-ksu/aadl/packages	line: 27 /isolette-ksu/aadl/packages/Devices.aadl	Xtext Check (fast)

for EMV2 annex subclause:

annex EMV2 
  {** 
  use types ErrorLibrary;
  use behavior KSU_Isolette::FailStop;
  error propagations
  internal_failure: out propagation {ItemOmission,ItemCommission};
  flows  --model error in detection and reporting
    inf: error source internal_failure{ItemOmission};
  end propagations;
  component error behavior
    detections  --in "failed" state put value on port internal_failure
      failed -[ ]-> internal_failure!;
  end component;
  properties  --set occurrence of detection failure
    EMV2::OccurrenceDistribution => Iso_Properties::DetectionRegulatorFailureRate 
      applies to inf;      
    --set failure rate for regulator
    EMV2::OccurrenceDistribution => Iso_Properties::RegulatorFailureRate 
      applies to fail;      
    EMV2::hazards => 
	   ( [	crossreference => "REMH A.5.1.4";
		  failure => "regulator failure not detected";
		  phases => ("all");
		  environment => "infant intensive care";
		  description => "failed, but not detected";
		  comment => "effect unknown";
			]) applies to inf;
	  EMV2::Severity => ARP4761::Minor applies to inf;
	  EMV2::Likelihood => ARP4761::ExtremelyRemote applies to inf;  
  **};

**Comment by reteprelief** [comment]
Works.
