### ISSUE TITLE
FTA Report - Default failure rate value is not noticeable 

### ISSUE THREAD

**Issue by fletchwsf** [osate/ErrorModelV2#71]
The FTA report uses a default value of "0.1" and skips the user provided value, for example 0.3 in the code shown below. This default value looks reasonable when reviewing the FTA outputs. It would clearer that a default value is being used if the value was not reasonable, for example "-0.999". OpenFTA will accept and process a negative value, and the output is not reasonable.  

EMV2 {**
...
properties
EMV2::OccurrenceDistribution => [ProbabilityValue => 0.3; Distribution => fixed;] applies to Failure;
...
**}

**Comment by reteprelief** [comment]
The fault tree generator now uses occurrence probability of zero as default if no explicit value was assigned.
