### ISSUE TITLE
EMV2::OccurrenceDistribution applied to error event causes spurios error marker

### ISSUE THREAD

**Issue by brlarson** [osate/ErrorModelV2#77]
I showed this problem to Julien at the AADL meeting in San Diego
![emv2error](https://cloud.githubusercontent.com/assets/1191402/6201889/179dcf20-b489-11e4-80a8-9293e3afc5eb.png)
This example was taken from the "PCA" project which I sent to Peter.

**Comment by reteprelief** [comment]
Works for association with error event.
