### ISSUE TITLE
Error when re-generating the grammar

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#79]
As for aadl, there is an error when re-generating the emv2 language with Java classes re-generated while they are already implemented with xtend (for example ErrorModelScopeProvider in org.osate.xtext.aadl2.errormodel.scoping)

**Comment by juli1** [comment]
@lwrage seems very similar to the issue reported for aadl2 yesterday

**Comment by lwrage** [comment]
Joe converted files to extend and didn't adjust the mwe2 file. For now just delete the generated Java files.
