### ISSUE TITLE
Using Elements of Port Arrays as Error Propagation Points (EMV2 Standard issue)

### ISSUE THREAD

**Issue by brlarson** [osate/ErrorModelV2#84]
David Deng of Adventium Labs discovered that there is no way to express elements of port arrays as error propagation points:

Also, I can't seem to find anywhere how one would refer to a specific
element in an array for error propagations. For example, I'd like to
say... -[2 ormore (inPort[0]{ValueError}, inPort[1]{ValueError}... etc
etc. OSATE gives me a syntax error. Is there a way to do this? Do I just
leave it as 2 ormore (inPort{ValueError})?

From the EMV2 standard:
error_propagation_point ::= feature_reference | binding_reference | propagation_point_identifier
feature_reference ::= ( { feature_group_identifier . }* feature_identifier ) | access

**Comment by reteprelief** [comment]
You are right, there is currently no way to specify an individual array element as error propagation. 
Do you have the need to identify individual elements or is x ormore of the array sufficient?

**Comment by brlarson** [comment]
I think we will need both individual elements and whole array.  Indexes can be just literals.
Whole array could be empty square brackets:  -[ 2 ormore (InPort[]{ValueError}) ]->
This could also be a handy use of slices:  -[ 2 ormore (InPort[0..2]{ValueError}) ]->
We're trying to have parametrized replication, 1x, 2x, 3x, etc. to do fault management trade-offs. 
There will also be some tricky connection patterns between arrays of components that have arrays of ports.  No doubt there will be other interesting error modeling of FT architectures.

**Comment by reteprelief** [comment]
Entered as issue at saeaadl/emv2#12
