### ISSUE TITLE
"use type " under annex EMV2 does not change color to look like systax in osate 2

### ISSUE THREAD

**Issue by qaiserms** [osate/ErrorModelV2#90]
I have this problem. Even if i had already added "with EMV2;" up in the code the key word "use" is not being highlighted. moreover it gives error as "mismatched input 'use' expecting 'end'", What I am missing ? ,, I have installed all plugin of EMV2, ErrorLibrary, and ErrorModelLIbrary. 

annex EMV2 {**
			Error propagations 
			  use types ErrorLibrary;
			  			
				**};

**Comment by juli1** [comment]
Hello
How did you installed OSATE? What version of OSATE do you have? It is possible to indicate your version, OS, and also the version of Java?

Thanks.

**Comment by qaiserms** [comment]
Well thanks Juli, I solved the problem by creating project in 'ErrorModel' folder in Osate2 'workspace'. But i have another issue if you can help me. I need help in replicating an error model in EMV2 that was declared and implemented in EMV1. Following is the code sample for EMV1 code and I want to understand that what will be the code in EMV2.

error model MyErrMdl
   features 
       feature1: initial error state:
       feature2: error state;
       fault: error event {occurrence => poisson L1};
end sw

error model implementation MyErrMdl.impl
    transitions 
        feature1 - [fault] -> feature2;
end MyErrMdl.impl

What will be the code for EMV2 for above example? can you guide ? ,, I am studying error model annex of Ana Rugina model for my masters thesis. 

will be grateful 

Best Regards
QaiserMS

**Comment by juli1** [comment]
Hello

I am definitively not an expert on emv1. Please ask on the AADL mailing list, this is not a bug against EMV2 but rather a question related the standard.

**Comment by qaiserms** [comment]
Hi Julien 

Correct me if i am wrong Sir, You are Dr.Juliean Delange from SEI right? It was nice to meet you at first place. And thanks for your time and help. Well it may sound odd w.r.t platform there may not exist any other way to communicate with you.  Can I request your email address? Actually I am a Masters Student at Sweden in Software Engineering and I am researching on Modelling TCAS II (Traffic Alert Collision and avoidance system) in AADL for dependability evaluation. It will be very fortunate for me if you are willing to guide me. So far, you are the first AADL expert who somehow talked to me by any means. (thanks to github). I make sure that if I be able to publish my work, your guidance will be credited as according to your choice Sir. my email address in qaami.5@gmail.com 

I am sorry to be irrelevant w.r.t topic of discussion. 

Best Regards
QaiserMS

**Comment by qaiserms** [comment]
Hi Julien 

In your "Wheel Brake System" explained in "AADL Fault Modeling and analysis within an ARP4761 Safety Assessment document " there is Figure 26. How it is possible to see all the sub-systems and processes within those sub-systems. My osate2 tool only shows 
![wbs](https://cloud.githubusercontent.com/assets/16530875/12254342/9bc5833e-b8e7-11e5-8a96-8ba64c64c85d.jpg)

**Comment by qaiserms** [comment]
What am I missing in above diagram to see it like this ? 
![fig26](https://cloud.githubusercontent.com/assets/16530875/12254381/1c2fea78-b8e8-11e5-8407-e0ef58008584.jpg)

**Comment by qaiserms** [comment]
I downloaded and installed osate 2 from links given in AADL wiki. I have the latest version 2.2.1 updated on github 5 days ago. Windows 7 operating system. and Java also updated 3-4 days back.

**Comment by juli1** [comment]
Hello,
Thanks for your e-mail. As explains previously, this is a bug tracking and I would prefer to use the AADL mailing lists to ask AADL-related questions. Please use our mailing list to reach out to the community and ask questions related to the language or the tools.

See https://wiki.sei.cmu.edu/aadl/index.php/Mailing_List

Thanks.

Julien.
