### ISSUE TITLE
Error propagations from subcomponents - unable to resolve reference

### ISSUE THREAD

**Issue by deyudeng** [osate/ErrorModelV2#94]
When connecting error propagations from a subcomponent to a parent component error propagation, unable to resolve reference error occurs.

```
package SubcomponentPortBugExample
public
with EMV2;
	abstract subcomponent
		features
			out1:	out data port;
	end subcomponent;
	abstract implementation subcomponent.impl
		annex EMV2{**
			use types ErrorLibrary;
			
			error propagations
				out1:					out propagation {ValueError};	
			end propagations;
		**};
	end subcomponent.impl;
----------------------------------------------------------------------------------
	abstract component
		features
			in1:	in data port;
			out1:	out data port;
	end component;
	abstract implementation component.impl
		subcomponents
			sub:			abstract subcomponent.impl;
		annex EMV2{**
			use types ErrorLibrary;
			use behavior ErrorLibrary::FailStop;
			
			error propagations
				in1:					in propagation {ValueError};
				out1:					out propagation {ValueError};
			end propagations;
			
			component error behavior
				propagations
					exampleName:		all-[(sub.out1{NoError})]-> out1{NoError};
					exampleName2:		all -[sub.out1{ValueError}]-> out1{NoError};
			end component;
		**};
	end component.impl;
end SubcomponentPortBugExample;
```

Error occurs when attempting to reference "sub.out1"

**Comment by reteprelief** [comment]
I ran across this last week as well. There is a legality rule for out propagation declarations that states:
L40	The error_condition_trigger of an outgoing error propagation declaration must only refer to error behavior events and incoming error propagation points. 

However, for error detection declarations we allow reference to outgoing propagations from subcomponents.

You example makes sense and I have put in an errata. A fix will be available in OSATE with the next build.

**Comment by reteprelief** [comment]
The testing release now resolves references to subcomponent propagations. 
We will be updating the fault impact analysis and fault tree analysis shortly to take advantage of this.
Still have to officially get it approved by the committee as errata.
