### ISSUE TITLE
getProbability raises an exception

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#99]
The getProbability function raises an issue after the last changes. When using it, it raises an exception because the property is not found. Before, the code was returning null when the property was not defined. See below.

If possible, it would be great to keep the null mechanism, to ensure backwards compatibility but also do not degrade performance (exception are way more costly than returning a null value, and if the analysis tool is querying for the probability a lot (such as the fault-tree mechanism), it will slow down the tool.

	public static double getProbability(NamedElement ci, NamedElement ne, TypeSet ts) {
		EMV2PropertyAssociation PA = EMV2Properties.getOccurenceDistributionProperty(ci, ne, ts);
		double prob = 0;
		if (PA != null) {
			prob = EMV2Properties.getOccurenceValue(PA);
		}
		return prob;
	}

**Comment by reteprelief** [comment]
seems to work now.
